### ISSUE TITLE
Styled Components

### ISSUE THREAD

**Issue by rnatu** [rnatu/github-blog#4]
# O texto fornece exemplos e informações sobre o uso do Styled Components, uma biblioteca popular para estilização de componentes em aplicações React. Ele aborda a instalação do Styled Components, sua utilização no mesmo arquivo e em arquivos externos, a aplicação de estilos condicionais com base em props e um exemplo adicional com um componente de botão personalizável.

[styled-components](https://styled-components.com/)
[global.ts](https://www.notion.so/global-ts-2d0893ec42dc4031a11b7b9edd453df6?pvs=21)

## Instalação

```bash
yarn add styled-components
```

Se utilizar typescript instalar a tipagem

```bash
yarn add @types/styled-components -D
```

## Utilização (No mesmo arquivo)

```jsx
import styled from "styled-components";

const Title = styled.h1`
  font-size: 64px;
  color: #8257e6;
`;

export function App() {
  return (
    <div className="App">
      <Title>
        Hello World
      </Title>
    </div>
  );
}
```

## Utilização no arquivo externo

Form.styles.ts

```css
**import styled from 'styled-components';

export const FormContainer = styled.form`
  h2 {
    color: var(--text-title);
    font-size: 1.5rem;
    margin-bottom: 2rem;
  }

  input {
    width: 100%;
    padding: 0 1.5rem;
    height: 4rem;
    border-radius: 0.25rem;

    border: 1px solid #D7D7D7;
    background-color: #E7E9EE;

    font-weight: 400;
    font-size: 1rem;

    &::placeholder {
      color: var(--text-body);
    }

    & + input {
      margin-top: 1rem;
    }
  }

  button[type="submit"] {
    width: 100%;
    padding: 0 1.5rem;
    height: 4rem;
    background: var(--green);
    color: #FFF;
    border: 0;
    font-size: 1rem;
    margin-top: 1.5rem;

    transition: filter 0.2s;

    &:hover {
      filter: brightness(0.9)
    }
  }

`;**
```

## Utilização com props

src/pages/history/index.tsx

```tsx
import { Status } from './styles';

export function History() {
  return (
    <>
      <h1>Meu histórico</h1>

      <Status statusColor="green">Concluído</Status>

      <Status statusColor="yellow">Concluído</Status>

      <Status statusColor="red">Concluído</Status>
    </>
  );
}
```

src/pages/history/styles.ts

```tsx
const STATUS_COLORS = {
  yellow: 'yellow-500',
  green: 'green-500',
  red: 'red-500',
} as const;

interface StatusProps {
  statusColor: keyof typeof STATUS_COLORS;
}

export const Status = styled.span<StatusProps>`
  display: flex;
  align-items: center;
  gap: 0.5rem;

  &::before {
    content: '';
   
    width: 0.5rem;
    height: 0.5rem;
    border-radius: 9999px;
    background: ${(props) => props.theme[STATUS_COLORS[props.statusColor]]};
  }
`;
```

## Outro Exemplo

Button.tsx

```tsx
import { ButtonContainer, ButtonVariant } from "./Button.styles";

interface ButtonProps {
  variant?: ButtonVariant;
}

export function Button({ variant = "success" }: ButtonProps) {
  return <ButtonContainer variant={variant}>Enviar</ButtonContainer>;
}
```

Button.styles.ts

```css
import styled, { css } from "styled-components";

export type ButtonVariant = "primary" | "secondary" | "danger" | "success";

interface ButtonContainerProps {
  variant: ButtonVariant;
}

const buttonVariants = {
  primary: "purple",
  secondary: "orange",
  danger: "red",
  success: "green",
};

export const ButtonContainer = styled.button<ButtonContainerProps>`
  height: 50px;
  width: 100px;

  ${(props) => {
    return css`
      background-color: ${buttonVariants[props.variant]};
    `;
  }}
`;
```
